language: rust
rust: stable
os: linux

cache:
  directories:
  - $HOME/.cargo
  - $HOME/gutenberg

install:
  - test -d $HOME/gutenberg/.git || git clone https://github.com/remexre/gutenberg.git $HOME/gutenberg --branch feature/runtime-syntax-loading
  - cargo install --force --path $HOME/gutenberg

script:
  - gutenberg build --base-url https://oftlisp.github.io/docs/
deploy:
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master
  provider: pages
  skip-cleanup: true
