language: rust
rust: stable
os: linux

cache:
  directories:
  - $HOME/.cargo
  - $HOME/gutenberg

install:
  - test -d $HOME/gutenberg || git clone https://github.com/Keats/gutenberg.git $HOME/gutenberg
  - cd $HOME/gutenberg
  - git submodule update --init
  - git submodule update --remote --merge
  - cd sublime_syntaxes
  - test -d Sublime-OftLisp || git clone https://github.com/oftlisp/Sublime-OftLisp.git
  - cd Sublime-OftLisp
  - git pull
  - cd ../../components/rendering
  - cargo run --example generate_sublime synpack ../../sublime_syntaxes ../../sublime_syntaxes/newlines.packdump ../../sublime_syntaxes/nonewlines.packdump
  - cd ../..
  - cargo install

script:
  - gutenberg build --base-url https://oftlisp.github.io/docs/
deploy:
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master
  provider: pages
  skip-cleanup: true
